name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-keyscan -p 5674 95.216.148.71 >> ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}" 
            ssh -o StrictHostKeyChecking=no root@95.216.148.71 -p 5674 << 'EOF'
            cd /root/infinite_games
            git pull
            pm2 delete validator
            source venv/bin/activate
            pip install -r requirements.txt
            export GRAFANA_API_KEY=glc_eyJvIjoiMTEzODYxOSIsIm4iOiJzdGFjay05NDcxNjEtaW50ZWdyYXRpb24tdmFsaSIsImsiOiJtWTNyTjVKY0NxOVg5djZnVTE0Sjk0NHQiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
            export TARGET_MONITOR_HOTKEY=5ED6jwDECEmNvSp98R2qyEUPHDv9pi14E6n3TS8CicD6YfhL
            pm2 start neurons/validator.py --name validator --interpreter python3 -- --netuid 6 --subtensor.network finney --wallet.name ckey --wallet.hotkey hkey --logging.debug --logging.trace
            EOF
