name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 5674 95.216.148.71 >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-agent }}
        run: |
          ssh -o StrictHostKeyChecking=no root@95.216.148.71 -p 5674 << 'EOF'
            cd /root/infinite_games
            git pull
            pm2 delete validator
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 start neurons/validator.py --name validator --interpreter python3 -- --netuid 6 --subtensor.network finney --wallet.name ckeyg --wallet.hotkey hkeyg --logging.debug --logging.trace
          EOF
